import type { Metadata } from 'next';
import { Nunito, Protest_Riot } from 'next/font/google';
import '../globals.css';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';

const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700', '800'],
  variable: '--font-nunito',
});

const protestRiot = Protest_Riot({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400'],
  variable: '--font-protestRiot',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-563K68LDS3" />
      <script
            dangerouslySetInnerHTML={{
              __html: `window.dataLayer = window.dataLayer || [];
 function gtag(){dataLayer.push(arguments);}
 gtag('js', new Date());
 gtag('config', 'G-563K68LDS3');
`,
            }}
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PMZWSRZJ');`,
            }}
          />


      <body
        className={`${nunito.variable} ${protestRiot.variable} ${nunito.className} antialiased relative`}
      >
        <noscript>
            <iframe
              src="https://www.googletagmanager.com/ns.html?id=GTM-PMZWSRZJ"
              height="0"
              width="0"
              style={{ display: 'none', visibility: 'hidden' }}
            />
          </noscript>
        <Navbar />
        <div className="pt-20">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
